spring.application.name=ERASM1
spring.datasource.url=jdbc:mysql://localhost:3306/erasm

spring.datasource.username=root

spring.datasource.password=nithesh

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080
logging.level.root=INFO
logging.level.com.erasm=INFO

logging.file.name=logs/erasm.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n